import { Material } from "@/types";

export const handCuratedDB: Material[] = [
  {
    id: "ss316l",
    name: "Stainless Steel 316L",
    category: "Metal",
    subcategory: "Austenitic Stainless",
    density_g_cm3: 7.99,
    tensile_strength_mpa: 515,
    yield_strength_mpa: 205,
    elastic_modulus_gpa: 193,
    hardness_vickers: 217,
    thermal_conductivity_w_mk: 16.3,
    specific_heat_j_gk: 0.5,
    melting_point_c: 1375,
    glass_transition_c: null,
    max_service_temp_c: 870,
    thermal_expansion_ppm_k: 16,
    electrical_resistivity_ohm_m: 7.4e-7,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 4,
    tags: ["marine", "medical", "food-grade"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "ti6al4v",
    name: "Ti-6Al-4V",
    category: "Metal",
    subcategory: "Titanium Alloy",
    density_g_cm3: 4.43,
    tensile_strength_mpa: 950,
    yield_strength_mpa: 880,
    elastic_modulus_gpa: 114,
    hardness_vickers: 349,
    thermal_conductivity_w_mk: 6.7,
    specific_heat_j_gk: 0.53,
    melting_point_c: 1660,
    glass_transition_c: null,
    max_service_temp_c: 315,
    thermal_expansion_ppm_k: 8.6,
    electrical_resistivity_ohm_m: 1.7e-6,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 35,
    tags: ["aerospace", "biomedical", "lightweight"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "inconel718",
    name: "Inconel 718",
    category: "Metal",
    subcategory: "Nickel Superalloy",
    density_g_cm3: 8.19,
    tensile_strength_mpa: 1375,
    yield_strength_mpa: 1100,
    elastic_modulus_gpa: 200,
    hardness_vickers: 430,
    thermal_conductivity_w_mk: 11.4,
    specific_heat_j_gk: 0.43,
    melting_point_c: 1336,
    glass_transition_c: null,
    max_service_temp_c: 700,
    thermal_expansion_ppm_k: 13,
    electrical_resistivity_ohm_m: 1.2e-6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 45,
    tags: ["aerospace", "high-temp", "jet-engine"],
    data_source: "Special Metals datasheet"
  },
  {
    id: "al6061t6",
    name: "Aluminum 6061-T6",
    category: "Metal",
    subcategory: "Aluminum Alloy",
    density_g_cm3: 2.7,
    tensile_strength_mpa: 310,
    yield_strength_mpa: 276,
    elastic_modulus_gpa: 68.9,
    hardness_vickers: 107,
    thermal_conductivity_w_mk: 167,
    specific_heat_j_gk: 0.896,
    melting_point_c: 652,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 23.6,
    electrical_resistivity_ohm_m: 3.7e-8,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 2.5,
    tags: ["lightweight", "structural", "automotive"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "al7075t6",
    name: "Aluminum 7075-T6",
    category: "Metal",
    subcategory: "Aluminum Alloy",
    density_g_cm3: 2.81,
    tensile_strength_mpa: 572,
    yield_strength_mpa: 503,
    elastic_modulus_gpa: 71.7,
    hardness_vickers: 175,
    thermal_conductivity_w_mk: 130,
    specific_heat_j_gk: 0.96,
    melting_point_c: 635,
    glass_transition_c: null,
    max_service_temp_c: 125,
    thermal_expansion_ppm_k: 23.4,
    electrical_resistivity_ohm_m: 5.1e-8,
    corrosion_resistance: "fair",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 3.5,
    tags: ["aerospace", "high-strength", "lightweight"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "copper_c110",
    name: "Copper C110",
    category: "Metal",
    subcategory: "Pure Copper",
    density_g_cm3: 8.94,
    tensile_strength_mpa: 220,
    yield_strength_mpa: 69,
    elastic_modulus_gpa: 117,
    hardness_vickers: 50,
    thermal_conductivity_w_mk: 388,
    specific_heat_j_gk: 0.385,
    melting_point_c: 1083,
    glass_transition_c: null,
    max_service_temp_c: 200,
    thermal_expansion_ppm_k: 17,
    electrical_resistivity_ohm_m: 1.7e-8,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 8,
    tags: ["electrical", "thermal", "conductive"],
    data_source: "Goodfellow Catalogue"
  },
  {
    id: "brass_c360",
    name: "Brass C360",
    category: "Metal",
    subcategory: "Leaded Brass",
    density_g_cm3: 8.5,
    tensile_strength_mpa: 385,
    yield_strength_mpa: 310,
    elastic_modulus_gpa: 97,
    hardness_vickers: 120,
    thermal_conductivity_w_mk: 115,
    specific_heat_j_gk: 0.38,
    melting_point_c: 900,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 20.5,
    electrical_resistivity_ohm_m: 6.2e-8,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 6,
    tags: ["machining", "plumbing", "fittings"],
    data_source: "MatWeb"
  },
  {
    id: "bronze_c932",
    name: "Bronze C932",
    category: "Metal",
    subcategory: "Bearing Bronze",
    density_g_cm3: 8.93,
    tensile_strength_mpa: 310,
    yield_strength_mpa: 152,
    elastic_modulus_gpa: 103,
    hardness_vickers: 75,
    thermal_conductivity_w_mk: 72,
    specific_heat_j_gk: 0.38,
    melting_point_c: 1000,
    glass_transition_c: null,
    max_service_temp_c: 180,
    thermal_expansion_ppm_k: 18,
    electrical_resistivity_ohm_m: 1.4e-7,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 10,
    tags: ["bearings", "bushings", "marine"],
    data_source: "MatWeb"
  },
  {
    id: "monel400",
    name: "Monel 400",
    category: "Metal",
    subcategory: "Nickel-Copper Alloy",
    density_g_cm3: 8.8,
    tensile_strength_mpa: 550,
    yield_strength_mpa: 240,
    elastic_modulus_gpa: 180,
    hardness_vickers: 140,
    thermal_conductivity_w_mk: 21.8,
    specific_heat_j_gk: 0.43,
    melting_point_c: 1350,
    glass_transition_c: null,
    max_service_temp_c: 480,
    thermal_expansion_ppm_k: 13.9,
    electrical_resistivity_ohm_m: 5.5e-7,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 30,
    tags: ["marine", "chemical", "seawater"],
    data_source: "Special Metals datasheet"
  },
  {
    id: "hastelloy_c276",
    name: "Hastelloy C-276",
    category: "Metal",
    subcategory: "Nickel Alloy",
    density_g_cm3: 8.89,
    tensile_strength_mpa: 690,
    yield_strength_mpa: 283,
    elastic_modulus_gpa: 205,
    hardness_vickers: 200,
    thermal_conductivity_w_mk: 10.2,
    specific_heat_j_gk: 0.42,
    melting_point_c: 1371,
    glass_transition_c: null,
    max_service_temp_c: 1040,
    thermal_expansion_ppm_k: 11.2,
    electrical_resistivity_ohm_m: 1.3e-6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 55,
    tags: ["chemical", "acid-resistant", "high-temp"],
    data_source: "Haynes International datasheet"
  },
  {
    id: "tungsten",
    name: "Tungsten W",
    category: "Metal",
    subcategory: "Refractory Metal",
    density_g_cm3: 19.3,
    tensile_strength_mpa: 1510,
    yield_strength_mpa: 750,
    elastic_modulus_gpa: 411,
    hardness_vickers: 3430,
    thermal_conductivity_w_mk: 173,
    specific_heat_j_gk: 0.13,
    melting_point_c: 3422,
    glass_transition_c: null,
    max_service_temp_c: 2000,
    thermal_expansion_ppm_k: 4.5,
    electrical_resistivity_ohm_m: 5.3e-8,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 55,
    tags: ["high-temp", "radiation-shielding", "heavy"],
    data_source: "Goodfellow Catalogue"
  },
  {
    id: "molybdenum",
    name: "Molybdenum Mo",
    category: "Metal",
    subcategory: "Refractory Metal",
    density_g_cm3: 10.22,
    tensile_strength_mpa: 630,
    yield_strength_mpa: 500,
    elastic_modulus_gpa: 330,
    hardness_vickers: 230,
    thermal_conductivity_w_mk: 138,
    specific_heat_j_gk: 0.25,
    melting_point_c: 2623,
    glass_transition_c: null,
    max_service_temp_c: 1600,
    thermal_expansion_ppm_k: 4.8,
    electrical_resistivity_ohm_m: 5.3e-8,
    corrosion_resistance: "fair",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 40,
    tags: ["high-temp", "electronics", "heating-elements"],
    data_source: "Goodfellow Catalogue"
  },
  {
    id: "beryllium_copper",
    name: "Beryllium Copper C17200",
    category: "Metal",
    subcategory: "Copper Alloy",
    density_g_cm3: 8.25,
    tensile_strength_mpa: 1380,
    yield_strength_mpa: 1170,
    elastic_modulus_gpa: 131,
    hardness_vickers: 400,
    thermal_conductivity_w_mk: 105,
    specific_heat_j_gk: 0.42,
    melting_point_c: 865,
    glass_transition_c: null,
    max_service_temp_c: 200,
    thermal_expansion_ppm_k: 17.8,
    electrical_resistivity_ohm_m: 7e-8,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 150,
    tags: ["springs", "connectors", "high-strength"],
    data_source: "Materion datasheet"
  },
  {
    id: "nickel200",
    name: "Nickel 200",
    category: "Metal",
    subcategory: "Pure Nickel",
    density_g_cm3: 8.89,
    tensile_strength_mpa: 380,
    yield_strength_mpa: 100,
    elastic_modulus_gpa: 204,
    hardness_vickers: 80,
    thermal_conductivity_w_mk: 70,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1455,
    glass_transition_c: null,
    max_service_temp_c: 315,
    thermal_expansion_ppm_k: 13.3,
    electrical_resistivity_ohm_m: 9.5e-8,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 20,
    tags: ["chemical", "food-processing", "alkaline"],
    data_source: "Special Metals datasheet"
  },
  {
    id: "tool_steel_d2",
    name: "Tool Steel D2",
    category: "Metal",
    subcategory: "Cold Work Tool Steel",
    density_g_cm3: 7.7,
    tensile_strength_mpa: 1520,
    yield_strength_mpa: 1380,
    elastic_modulus_gpa: 210,
    hardness_vickers: 700,
    thermal_conductivity_w_mk: 20,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1421,
    glass_transition_c: null,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 10.7,
    electrical_resistivity_ohm_m: 4.8e-7,
    corrosion_resistance: "fair",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 8,
    tags: ["tooling", "dies", "cutting"],
    data_source: "ASM Handbook Vol 1"
  },
  {
    id: "spring_steel_1095",
    name: "Spring Steel 1095",
    category: "Metal",
    subcategory: "High Carbon Steel",
    density_g_cm3: 7.83,
    tensile_strength_mpa: 1015,
    yield_strength_mpa: 844,
    elastic_modulus_gpa: 207,
    hardness_vickers: 293,
    thermal_conductivity_w_mk: 46,
    specific_heat_j_gk: 0.49,
    melting_point_c: 1425,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 11,
    electrical_resistivity_ohm_m: 2e-7,
    corrosion_resistance: "poor",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 1.5,
    tags: ["springs", "blades", "structural"],
    data_source: "ASM Handbook Vol 1"
  },
  {
    id: "carbon_steel_1020",
    name: "Carbon Steel 1020",
    category: "Metal",
    subcategory: "Low Carbon Steel",
    density_g_cm3: 7.87,
    tensile_strength_mpa: 394,
    yield_strength_mpa: 294,
    elastic_modulus_gpa: 200,
    hardness_vickers: 111,
    thermal_conductivity_w_mk: 51.9,
    specific_heat_j_gk: 0.49,
    melting_point_c: 1515,
    glass_transition_c: null,
    max_service_temp_c: 400,
    thermal_expansion_ppm_k: 11.7,
    electrical_resistivity_ohm_m: 1.6e-7,
    corrosion_resistance: "poor",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 0.8,
    tags: ["structural", "general-purpose", "cheap"],
    data_source: "ASM Handbook Vol 1"
  },
  {
    id: "grey_cast_iron",
    name: "Grey Cast Iron",
    category: "Metal",
    subcategory: "Cast Iron",
    density_g_cm3: 7.15,
    tensile_strength_mpa: 200,
    yield_strength_mpa: 120,
    elastic_modulus_gpa: 100,
    hardness_vickers: 207,
    thermal_conductivity_w_mk: 54,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1175,
    glass_transition_c: null,
    max_service_temp_c: 300,
    thermal_expansion_ppm_k: 11,
    electrical_resistivity_ohm_m: 1e-6,
    corrosion_resistance: "poor",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 0.5,
    tags: ["casting", "vibration-damping", "cheap"],
    data_source: "ASM Handbook Vol 1"
  },
  {
    id: "pla",
    name: "PLA",
    category: "Polymer",
    subcategory: "Biopolymer / FDM",
    density_g_cm3: 1.24,
    tensile_strength_mpa: 50,
    yield_strength_mpa: 48,
    elastic_modulus_gpa: 3.5,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.13,
    specific_heat_j_gk: 1.8,
    melting_point_c: null,
    glass_transition_c: 60,
    max_service_temp_c: 55,
    thermal_expansion_ppm_k: 68,
    electrical_resistivity_ohm_m: 1e16,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "excellent",
    cost_usd_kg: 20,
    tags: ["3d-printing", "biodegradable", "hobby"],
    data_source: "MatWeb"
  },
  {
    id: "abs",
    name: "ABS",
    category: "Polymer",
    subcategory: "Thermoplastic / FDM",
    density_g_cm3: 1.05,
    tensile_strength_mpa: 40,
    yield_strength_mpa: 38,
    elastic_modulus_gpa: 2.3,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.17,
    specific_heat_j_gk: 1.4,
    melting_point_c: null,
    glass_transition_c: 105,
    max_service_temp_c: 80,
    thermal_expansion_ppm_k: 73,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "good",
    cost_usd_kg: 18,
    tags: ["3d-printing", "consumer", "impact-resistant"],
    data_source: "MatWeb"
  },
  {
    id: "petg",
    name: "PETG",
    category: "Polymer",
    subcategory: "Thermoplastic / FDM",
    density_g_cm3: 1.27,
    tensile_strength_mpa: 53,
    yield_strength_mpa: 47,
    elastic_modulus_gpa: 2.1,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.29,
    specific_heat_j_gk: 1.2,
    melting_point_c: null,
    glass_transition_c: 80,
    max_service_temp_c: 85,
    thermal_expansion_ppm_k: 60,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "excellent",
    cost_usd_kg: 25,
    tags: ["3d-printing", "food-safe", "chemical-resistant"],
    data_source: "MatWeb / Polymaker datasheet"
  },
  {
    id: "nylon_pa12",
    name: "Nylon PA12",
    category: "Polymer",
    subcategory: "Polyamide / FDM",
    density_g_cm3: 1.01,
    tensile_strength_mpa: 48,
    yield_strength_mpa: 40,
    elastic_modulus_gpa: 1.6,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.23,
    specific_heat_j_gk: 1.7,
    melting_point_c: null,
    glass_transition_c: 155,
    max_service_temp_c: 110,
    thermal_expansion_ppm_k: 100,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "good",
    cost_usd_kg: 60,
    tags: ["3d-printing", "flexible", "lightweight"],
    data_source: "EOS datasheet"
  },
  {
    id: "polycarbonate",
    name: "Polycarbonate",
    category: "Polymer",
    subcategory: "Thermoplastic / FDM",
    density_g_cm3: 1.2,
    tensile_strength_mpa: 65,
    yield_strength_mpa: 60,
    elastic_modulus_gpa: 2.4,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.21,
    specific_heat_j_gk: 1.25,
    melting_point_c: null,
    glass_transition_c: 147,
    max_service_temp_c: 120,
    thermal_expansion_ppm_k: 65,
    electrical_resistivity_ohm_m: 1e16,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "good",
    cost_usd_kg: 45,
    tags: ["transparent", "impact-resistant", "optical"],
    data_source: "MatWeb"
  },
  {
    id: "peek",
    name: "PEEK",
    category: "Polymer",
    subcategory: "High-Performance Polymer",
    density_g_cm3: 1.32,
    tensile_strength_mpa: 100,
    yield_strength_mpa: 91,
    elastic_modulus_gpa: 3.6,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1.34,
    melting_point_c: null,
    glass_transition_c: 143,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 47,
    electrical_resistivity_ohm_m: 4.9e13,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 90,
    tags: ["aerospace", "medical", "chemical-resistant"],
    data_source: "Victrex datasheet"
  },
  {
    id: "ultem9085",
    name: "Ultem 9085",
    category: "Polymer",
    subcategory: "PEI / FDM",
    density_g_cm3: 1.34,
    tensile_strength_mpa: 71,
    yield_strength_mpa: 68,
    elastic_modulus_gpa: 2.5,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.17,
    specific_heat_j_gk: 1.3,
    melting_point_c: null,
    glass_transition_c: 186,
    max_service_temp_c: 170,
    thermal_expansion_ppm_k: 47,
    electrical_resistivity_ohm_m: 5e13,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 350,
    tags: ["aerospace", "flame-retardant", "fused-deposition"],
    data_source: "Stratasys datasheet"
  },
  {
    id: "ptfe",
    name: "PTFE",
    category: "Polymer",
    subcategory: "Fluoropolymer",
    density_g_cm3: 2.2,
    tensile_strength_mpa: 25,
    yield_strength_mpa: 23,
    elastic_modulus_gpa: 0.5,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1,
    melting_point_c: null,
    glass_transition_c: 127,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 135,
    electrical_resistivity_ohm_m: 1e18,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 25,
    tags: ["chemical-resistant", "non-stick", "seals"],
    data_source: "DuPont Teflon datasheet"
  },
  {
    id: "hdpe",
    name: "HDPE",
    category: "Polymer",
    subcategory: "Thermoplastic",
    density_g_cm3: 0.95,
    tensile_strength_mpa: 30,
    yield_strength_mpa: 27,
    elastic_modulus_gpa: 1,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.44,
    specific_heat_j_gk: 1.8,
    melting_point_c: null,
    glass_transition_c: -120,
    max_service_temp_c: 80,
    thermal_expansion_ppm_k: 130,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 1.5,
    tags: ["chemical", "piping", "food-safe"],
    data_source: "MatWeb"
  },
  {
    id: "delrin_pom",
    name: "Delrin (POM)",
    category: "Polymer",
    subcategory: "Acetal / Thermoplastic",
    density_g_cm3: 1.41,
    tensile_strength_mpa: 68,
    yield_strength_mpa: 60,
    elastic_modulus_gpa: 3.1,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.37,
    specific_heat_j_gk: 1.46,
    melting_point_c: null,
    glass_transition_c: -50,
    max_service_temp_c: 90,
    thermal_expansion_ppm_k: 110,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "good",
    cost_usd_kg: 5,
    tags: ["gears", "bearings", "precision-parts"],
    data_source: "DuPont Delrin datasheet"
  },
  {
    id: "polysulfone",
    name: "Polysulfone",
    category: "Polymer",
    subcategory: "High-Performance Thermoplastic",
    density_g_cm3: 1.24,
    tensile_strength_mpa: 70,
    yield_strength_mpa: 65,
    elastic_modulus_gpa: 2.7,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.26,
    specific_heat_j_gk: 1.03,
    melting_point_c: null,
    glass_transition_c: 185,
    max_service_temp_c: 160,
    thermal_expansion_ppm_k: 55,
    electrical_resistivity_ohm_m: 5e16,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "poor",
    cost_usd_kg: 40,
    tags: ["medical", "membrane", "high-temp"],
    data_source: "MatWeb"
  },
  {
    id: "alumina_al2o3",
    name: "Alumina Al2O3",
    category: "Ceramic",
    subcategory: "Oxide Ceramic",
    density_g_cm3: 3.9,
    tensile_strength_mpa: 300,
    yield_strength_mpa: 300,
    elastic_modulus_gpa: 370,
    hardness_vickers: 1440,
    thermal_conductivity_w_mk: 30,
    specific_heat_j_gk: 0.88,
    melting_point_c: 2072,
    glass_transition_c: null,
    max_service_temp_c: 1600,
    thermal_expansion_ppm_k: 8.1,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 15,
    tags: ["wear-resistant", "electrical-insulation", "high-temp"],
    data_source: "MatWeb / CoorsTek datasheet"
  },
  {
    id: "zirconia_zro2",
    name: "Zirconia ZrO2",
    category: "Ceramic",
    subcategory: "Oxide Ceramic",
    density_g_cm3: 6.05,
    tensile_strength_mpa: 900,
    yield_strength_mpa: 900,
    elastic_modulus_gpa: 200,
    hardness_vickers: 1200,
    thermal_conductivity_w_mk: 2.7,
    specific_heat_j_gk: 0.46,
    melting_point_c: 2715,
    glass_transition_c: null,
    max_service_temp_c: 2400,
    thermal_expansion_ppm_k: 10.5,
    electrical_resistivity_ohm_m: 1e10,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 50,
    tags: ["dental", "thermal-barrier", "tough-ceramic"],
    data_source: "MatWeb"
  },
  {
    id: "sic",
    name: "Silicon Carbide SiC",
    category: "Ceramic",
    subcategory: "Non-Oxide Ceramic",
    density_g_cm3: 3.21,
    tensile_strength_mpa: 410,
    yield_strength_mpa: 410,
    elastic_modulus_gpa: 410,
    hardness_vickers: 2800,
    thermal_conductivity_w_mk: 120,
    specific_heat_j_gk: 0.67,
    melting_point_c: 2730,
    glass_transition_c: null,
    max_service_temp_c: 1600,
    thermal_expansion_ppm_k: 4,
    electrical_resistivity_ohm_m: 1e2,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 30,
    tags: ["abrasive", "semiconductor", "high-temp"],
    data_source: "NASA TPSX"
  },
  {
    id: "si3n4",
    name: "Silicon Nitride Si3N4",
    category: "Ceramic",
    subcategory: "Non-Oxide Ceramic",
    density_g_cm3: 3.27,
    tensile_strength_mpa: 700,
    yield_strength_mpa: 700,
    elastic_modulus_gpa: 304,
    hardness_vickers: 1700,
    thermal_conductivity_w_mk: 30,
    specific_heat_j_gk: 0.71,
    melting_point_c: 1900,
    glass_transition_c: null,
    max_service_temp_c: 1300,
    thermal_expansion_ppm_k: 3.2,
    electrical_resistivity_ohm_m: 1e13,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 80,
    tags: ["bearings", "cutting-tools", "high-temp"],
    data_source: "MatWeb"
  },
  {
    id: "boron_nitride",
    name: "Boron Nitride BN",
    category: "Ceramic",
    subcategory: "Non-Oxide Ceramic",
    density_g_cm3: 2.27,
    tensile_strength_mpa: 100,
    yield_strength_mpa: 100,
    elastic_modulus_gpa: 90,
    hardness_vickers: 10,
    thermal_conductivity_w_mk: 30,
    specific_heat_j_gk: 0.79,
    melting_point_c: 3000,
    glass_transition_c: null,
    max_service_temp_c: 900,
    thermal_expansion_ppm_k: 1,
    electrical_resistivity_ohm_m: 1e11,
    corrosion_resistance: "excellent",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 100,
    tags: ["lubricant", "thermal-management", "insulation"],
    data_source: "MatWeb"
  },
  {
    id: "cfrp",
    name: "CFRP (Carbon Fiber UD)",
    category: "Composite",
    subcategory: "Carbon Fiber Reinforced Polymer",
    density_g_cm3: 1.6,
    tensile_strength_mpa: 1500,
    yield_strength_mpa: 1500,
    elastic_modulus_gpa: 135,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 7,
    specific_heat_j_gk: 0.84,
    melting_point_c: null,
    glass_transition_c: 120,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 0.5,
    electrical_resistivity_ohm_m: 1.5e-5,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 80,
    tags: ["aerospace", "lightweight", "ultra-high-strength"],
    data_source: "Hexcel datasheet"
  },
  {
    id: "gfrp",
    name: "GFRP (Glass Fiber Epoxy)",
    category: "Composite",
    subcategory: "Glass Fiber Reinforced Polymer",
    density_g_cm3: 1.8,
    tensile_strength_mpa: 440,
    yield_strength_mpa: 440,
    elastic_modulus_gpa: 20,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.35,
    specific_heat_j_gk: 1,
    melting_point_c: null,
    glass_transition_c: 120,
    max_service_temp_c: 130,
    thermal_expansion_ppm_k: 14,
    electrical_resistivity_ohm_m: 1e11,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 15,
    tags: ["marine", "electrical-insulation", "structural"],
    data_source: "MatWeb"
  },
  {
    id: "kevlar_epoxy",
    name: "Kevlar/Epoxy",
    category: "Composite",
    subcategory: "Aramid Fiber Reinforced Polymer",
    density_g_cm3: 1.38,
    tensile_strength_mpa: 1380,
    yield_strength_mpa: 1380,
    elastic_modulus_gpa: 76,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.04,
    specific_heat_j_gk: 1.4,
    melting_point_c: null,
    glass_transition_c: 180,
    max_service_temp_c: 180,
    thermal_expansion_ppm_k: 2,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 60,
    tags: ["ballistic", "lightweight", "impact-resistant"],
    data_source: "DuPont Kevlar datasheet"
  },
  {
    id: "carbon_carbon",
    name: "Carbon-Carbon Composite",
    category: "Composite",
    subcategory: "C/C Composite",
    density_g_cm3: 1.8,
    tensile_strength_mpa: 350,
    yield_strength_mpa: 350,
    elastic_modulus_gpa: 100,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 120,
    specific_heat_j_gk: 0.84,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 3000,
    thermal_expansion_ppm_k: 1,
    electrical_resistivity_ohm_m: 1.5e-5,
    corrosion_resistance: "poor",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 500,
    tags: ["aerospace", "brake-discs", "extreme-temp"],
    data_source: "NASA TPSX"
  },
  {
    id: "sn63pb37",
    name: "Sn63Pb37 Solder",
    category: "Solder",
    subcategory: "Tin-Lead Eutectic",
    density_g_cm3: 8.4,
    tensile_strength_mpa: 35,
    yield_strength_mpa: 25,
    elastic_modulus_gpa: 30,
    hardness_vickers: 14,
    thermal_conductivity_w_mk: 50,
    specific_heat_j_gk: 0.17,
    melting_point_c: 183,
    glass_transition_c: null,
    max_service_temp_c: 100,
    thermal_expansion_ppm_k: 25,
    electrical_resistivity_ohm_m: 1.4e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 10,
    tags: ["electronics", "pcb", "solder"],
    data_source: "MatWeb"
  },
  {
    id: "sac305",
    name: "SAC305 (Sn-Ag-Cu)",
    category: "Solder",
    subcategory: "Lead-Free Solder",
    density_g_cm3: 7.38,
    tensile_strength_mpa: 40,
    yield_strength_mpa: 30,
    elastic_modulus_gpa: 50,
    hardness_vickers: 15,
    thermal_conductivity_w_mk: 60,
    specific_heat_j_gk: 0.23,
    melting_point_c: 218,
    glass_transition_c: null,
    max_service_temp_c: 120,
    thermal_expansion_ppm_k: 21,
    electrical_resistivity_ohm_m: 1.2e-7,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 25,
    tags: ["lead-free", "electronics", "rohs"],
    data_source: "MatWeb"
  },
  {
    id: "auSn20",
    name: "Gold-Tin AuSn20",
    category: "Solder",
    subcategory: "Hard Solder",
    density_g_cm3: 14.7,
    tensile_strength_mpa: 275,
    yield_strength_mpa: 260,
    elastic_modulus_gpa: 68,
    hardness_vickers: 200,
    thermal_conductivity_w_mk: 57,
    specific_heat_j_gk: 0.15,
    melting_point_c: 280,
    glass_transition_c: null,
    max_service_temp_c: 200,
    thermal_expansion_ppm_k: 15.9,
    electrical_resistivity_ohm_m: 1.6e-7,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 40000,
    tags: ["microelectronics", "hermetic", "high-reliability"],
    data_source: "Indium Corporation datasheet"
  },
  {
    id: "bag7",
    name: "Silver Braze BAg-7",
    category: "Solder",
    subcategory: "Silver Braze Alloy",
    density_g_cm3: 9.2,
    tensile_strength_mpa: 350,
    yield_strength_mpa: 250,
    elastic_modulus_gpa: 80,
    hardness_vickers: 70,
    thermal_conductivity_w_mk: 70,
    specific_heat_j_gk: 0.24,
    melting_point_c: 700,
    glass_transition_c: null,
    max_service_temp_c: 300,
    thermal_expansion_ppm_k: 19,
    electrical_resistivity_ohm_m: 3e-7,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 800,
    tags: ["brazing", "hvac", "stainless-joining"],
    data_source: "Lucas-Milhaupt datasheet"
  },
  {
    id: "al2024t3",
    name: "Aluminum 2024-T3",
    category: "Metal",
    subcategory: "Aluminum Alloy",
    density_g_cm3: 2.78,
    tensile_strength_mpa: 483,
    yield_strength_mpa: 345,
    elastic_modulus_gpa: 73.1,
    hardness_vickers: 130,
    thermal_conductivity_w_mk: 121,
    specific_heat_j_gk: 0.875,
    melting_point_c: 638,
    glass_transition_c: null,
    max_service_temp_c: 130,
    thermal_expansion_ppm_k: 23.2,
    electrical_resistivity_ohm_m: 5.8e-8,
    corrosion_resistance: "fair",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 4,
    tags: ["aerospace", "structural", "high-strength"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "invar36",
    name: "Invar 36",
    category: "Metal",
    subcategory: "Nickel-Iron Alloy",
    density_g_cm3: 8.05,
    tensile_strength_mpa: 485,
    yield_strength_mpa: 276,
    elastic_modulus_gpa: 141,
    hardness_vickers: 160,
    thermal_conductivity_w_mk: 10.5,
    specific_heat_j_gk: 0.515,
    melting_point_c: 1425,
    glass_transition_c: null,
    max_service_temp_c: 230,
    thermal_expansion_ppm_k: 1.3,
    electrical_resistivity_ohm_m: 8.2e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 35,
    tags: ["low-expansion", "precision", "metrology", "optics"],
    data_source: "Special Metals datasheet"
  },
  {
    id: "kovar",
    name: "Kovar (ASTM F15)",
    category: "Metal",
    subcategory: "Fe-Ni-Co Alloy",
    density_g_cm3: 8.36,
    tensile_strength_mpa: 517,
    yield_strength_mpa: 345,
    elastic_modulus_gpa: 138,
    hardness_vickers: 170,
    thermal_conductivity_w_mk: 17.3,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1450,
    glass_transition_c: null,
    max_service_temp_c: 450,
    thermal_expansion_ppm_k: 5.1,
    electrical_resistivity_ohm_m: 4.9e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 80,
    tags: ["hermetic-sealing", "glass-to-metal", "electronics"],
    data_source: "Carpenter Technology datasheet"
  },
  {
    id: "ti_cp2",
    name: "Titanium Grade 2 (CP)",
    category: "Metal",
    subcategory: "Pure Titanium",
    density_g_cm3: 4.51,
    tensile_strength_mpa: 345,
    yield_strength_mpa: 275,
    elastic_modulus_gpa: 103,
    hardness_vickers: 145,
    thermal_conductivity_w_mk: 16.4,
    specific_heat_j_gk: 0.528,
    melting_point_c: 1668,
    glass_transition_c: null,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 8.9,
    electrical_resistivity_ohm_m: 5.6e-7,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 25,
    tags: ["biomedical", "chemical", "corrosion-resistant"],
    data_source: "ASTM B265"
  },
  {
    id: "maraging300",
    name: "Maraging Steel 300",
    category: "Metal",
    subcategory: "Maraging Steel",
    density_g_cm3: 8,
    tensile_strength_mpa: 1900,
    yield_strength_mpa: 1800,
    elastic_modulus_gpa: 190,
    hardness_vickers: 575,
    thermal_conductivity_w_mk: 25,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1430,
    glass_transition_c: null,
    max_service_temp_c: 400,
    thermal_expansion_ppm_k: 10,
    electrical_resistivity_ohm_m: 6e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 120,
    tags: ["ultra-high-strength", "aerospace", "tooling"],
    data_source: "Carpenter Technology datasheet"
  },
  {
    id: "waspaloy",
    name: "Waspaloy",
    category: "Metal",
    subcategory: "Nickel Superalloy",
    density_g_cm3: 8.19,
    tensile_strength_mpa: 1275,
    yield_strength_mpa: 795,
    elastic_modulus_gpa: 213,
    hardness_vickers: 365,
    thermal_conductivity_w_mk: 13.4,
    specific_heat_j_gk: 0.42,
    melting_point_c: 1330,
    glass_transition_c: null,
    max_service_temp_c: 980,
    thermal_expansion_ppm_k: 12.7,
    electrical_resistivity_ohm_m: 1.27e-6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 90,
    tags: ["aerospace", "turbine", "jet-engine", "high-temp"],
    data_source: "Special Metals datasheet"
  },
  {
    id: "mg_az31b",
    name: "Magnesium AZ31B",
    category: "Metal",
    subcategory: "Magnesium Alloy",
    density_g_cm3: 1.77,
    tensile_strength_mpa: 260,
    yield_strength_mpa: 200,
    elastic_modulus_gpa: 44.8,
    hardness_vickers: 73,
    thermal_conductivity_w_mk: 96,
    specific_heat_j_gk: 1.02,
    melting_point_c: 630,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 26,
    electrical_resistivity_ohm_m: 9.2e-8,
    corrosion_resistance: "poor",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 3,
    tags: ["ultra-lightweight", "aerospace", "electronics-housing"],
    data_source: "ASM Handbook Vol 2"
  },
  {
    id: "nitinol",
    name: "Nitinol (NiTi 50-50)",
    category: "Metal",
    subcategory: "Shape Memory Alloy",
    density_g_cm3: 6.45,
    tensile_strength_mpa: 900,
    yield_strength_mpa: 560,
    elastic_modulus_gpa: 83,
    hardness_vickers: 300,
    thermal_conductivity_w_mk: 18,
    specific_heat_j_gk: 0.84,
    melting_point_c: 1310,
    glass_transition_c: null,
    max_service_temp_c: 100,
    thermal_expansion_ppm_k: 11,
    electrical_resistivity_ohm_m: 8.2e-7,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 300,
    tags: ["shape-memory", "medical", "actuator", "superelastic"],
    data_source: "NDC Nitinol datasheet"
  },
  {
    id: "etp_c11000",
    name: "ETP Copper C11000",
    category: "Metal",
    subcategory: "Electrolytic Tough Pitch Copper",
    density_g_cm3: 8.96,
    tensile_strength_mpa: 235,
    yield_strength_mpa: 70,
    elastic_modulus_gpa: 117,
    hardness_vickers: 55,
    thermal_conductivity_w_mk: 391,
    specific_heat_j_gk: 0.385,
    melting_point_c: 1084,
    glass_transition_c: null,
    max_service_temp_c: 220,
    thermal_expansion_ppm_k: 16.7,
    electrical_resistivity_ohm_m: 1.72e-8,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 8.5,
    tags: ["electrical", "busbar", "conductive", "probe-tip"],
    data_source: "CDA / Goodfellow datasheet"
  },
  {
    id: "asa",
    name: "ASA",
    category: "Polymer",
    subcategory: "Thermoplastic / FDM",
    density_g_cm3: 1.07,
    tensile_strength_mpa: 48,
    yield_strength_mpa: 44,
    elastic_modulus_gpa: 2.1,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.17,
    specific_heat_j_gk: 1.3,
    melting_point_c: null,
    glass_transition_c: 100,
    max_service_temp_c: 98,
    thermal_expansion_ppm_k: 70,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "good",
    cost_usd_kg: 30,
    tags: ["3d-printing", "uv-resistant", "outdoor", "automotive"],
    data_source: "MatWeb"
  },
  {
    id: "pekk",
    name: "PEKK",
    category: "Polymer",
    subcategory: "High-Perf Polymer / FDM",
    density_g_cm3: 1.3,
    tensile_strength_mpa: 110,
    yield_strength_mpa: 99,
    elastic_modulus_gpa: 4.1,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.29,
    specific_heat_j_gk: 1.34,
    melting_point_c: null,
    glass_transition_c: 165,
    max_service_temp_c: 280,
    thermal_expansion_ppm_k: 40,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 120,
    tags: ["aerospace", "high-temp", "PAEK", "additive"],
    data_source: "Arkema Kepstan datasheet"
  },
  {
    id: "tpu",
    name: "TPU",
    category: "Polymer",
    subcategory: "Elastomeric / FDM",
    density_g_cm3: 1.21,
    tensile_strength_mpa: 35,
    yield_strength_mpa: 15,
    elastic_modulus_gpa: 0.05,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.22,
    specific_heat_j_gk: 1.8,
    melting_point_c: null,
    glass_transition_c: -30,
    max_service_temp_c: 80,
    thermal_expansion_ppm_k: 150,
    electrical_resistivity_ohm_m: 1e10,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "good",
    cost_usd_kg: 40,
    tags: ["flexible", "3d-printing", "gaskets", "wheels"],
    data_source: "MatWeb"
  },
  {
    id: "pps",
    name: "PPS (Polyphenylene Sulfide)",
    category: "Polymer",
    subcategory: "High-Perf Polymer",
    density_g_cm3: 1.35,
    tensile_strength_mpa: 90,
    yield_strength_mpa: 83,
    elastic_modulus_gpa: 3.8,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.29,
    specific_heat_j_gk: 1.09,
    melting_point_c: null,
    glass_transition_c: 85,
    max_service_temp_c: 220,
    thermal_expansion_ppm_k: 49,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 35,
    tags: ["chemical-resistant", "high-temp", "automotive"],
    data_source: "Solvay Ryton datasheet"
  },
  {
    id: "ultem1010",
    name: "Ultem 1010",
    category: "Polymer",
    subcategory: "PEI / High-Perf FDM",
    density_g_cm3: 1.27,
    tensile_strength_mpa: 91,
    yield_strength_mpa: 85,
    elastic_modulus_gpa: 3.6,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.21,
    specific_heat_j_gk: 1.3,
    melting_point_c: null,
    glass_transition_c: 217,
    max_service_temp_c: 210,
    thermal_expansion_ppm_k: 47,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 400,
    tags: ["autoclavable", "food-contact", "high-temp-fdm"],
    data_source: "Stratasys datasheet"
  },
  {
    id: "pmma",
    name: "PMMA (Acrylic)",
    category: "Polymer",
    subcategory: "Thermoplastic",
    density_g_cm3: 1.19,
    tensile_strength_mpa: 72,
    yield_strength_mpa: 62,
    elastic_modulus_gpa: 3.2,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.19,
    specific_heat_j_gk: 1.46,
    melting_point_c: null,
    glass_transition_c: 105,
    max_service_temp_c: 90,
    thermal_expansion_ppm_k: 70,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "poor",
    cost_usd_kg: 4,
    tags: ["optical", "transparent", "display", "signage"],
    data_source: "MatWeb"
  },
  {
    id: "pvdf",
    name: "PVDF",
    category: "Polymer",
    subcategory: "Fluoropolymer",
    density_g_cm3: 1.78,
    tensile_strength_mpa: 55,
    yield_strength_mpa: 40,
    elastic_modulus_gpa: 2.5,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.19,
    specific_heat_j_gk: 1.28,
    melting_point_c: null,
    glass_transition_c: -40,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 127,
    electrical_resistivity_ohm_m: 2e13,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "poor",
    cost_usd_kg: 30,
    tags: ["chemical", "piezoelectric", "semiconductor", "piping"],
    data_source: "Solvay Solef datasheet"
  },
  {
    id: "tungsten_carbide",
    name: "Tungsten Carbide WC-Co 6%",
    category: "Ceramic",
    subcategory: "Cemented Carbide",
    density_g_cm3: 14.9,
    tensile_strength_mpa: 1800,
    yield_strength_mpa: 1800,
    elastic_modulus_gpa: 630,
    hardness_vickers: 1600,
    thermal_conductivity_w_mk: 100,
    specific_heat_j_gk: 0.2,
    melting_point_c: 2870,
    glass_transition_c: null,
    max_service_temp_c: 500,
    thermal_expansion_ppm_k: 5.2,
    electrical_resistivity_ohm_m: 2e-7,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 100,
    tags: ["cutting-tools", "wear-resistant", "dies", "mining"],
    data_source: "Kennametal datasheet"
  },
  {
    id: "cordierite",
    name: "Cordierite",
    category: "Ceramic",
    subcategory: "Silicate Ceramic",
    density_g_cm3: 2.6,
    tensile_strength_mpa: 170,
    yield_strength_mpa: 170,
    elastic_modulus_gpa: 138,
    hardness_vickers: 900,
    thermal_conductivity_w_mk: 3,
    specific_heat_j_gk: 0.84,
    melting_point_c: 1460,
    glass_transition_c: null,
    max_service_temp_c: 1200,
    thermal_expansion_ppm_k: 1.5,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 20,
    tags: ["thermal-shock", "kiln", "substrate", "low-expansion"],
    data_source: "MatWeb"
  },
  {
    id: "sic_sic",
    name: "SiC/SiC Ceramic Matrix Composite",
    category: "Composite",
    subcategory: "CMC",
    density_g_cm3: 2.7,
    tensile_strength_mpa: 400,
    yield_strength_mpa: 400,
    elastic_modulus_gpa: 220,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 20,
    specific_heat_j_gk: 0.75,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 1400,
    thermal_expansion_ppm_k: 4.5,
    electrical_resistivity_ohm_m: 1e6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 2000,
    tags: ["aerospace", "turbine", "nuclear", "ultra-high-temp"],
    data_source: "GE Aviation CMC datasheet"
  },
  {
    id: "boron_cfrp",
    name: "Boron/Epoxy Composite",
    category: "Composite",
    subcategory: "Boron Fiber Reinforced",
    density_g_cm3: 2,
    tensile_strength_mpa: 1400,
    yield_strength_mpa: 1400,
    elastic_modulus_gpa: 210,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 2,
    specific_heat_j_gk: 1.05,
    melting_point_c: null,
    glass_transition_c: 150,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 4.5,
    electrical_resistivity_ohm_m: 1e10,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 400,
    tags: ["aerospace", "ultra-stiff", "fighter-aircraft"],
    data_source: "Textron datasheet"
  },
  {
    id: "inbi57",
    name: "In57Bi43 Low-Temp Solder",
    category: "Solder",
    subcategory: "Indium-Bismuth",
    density_g_cm3: 7.99,
    tensile_strength_mpa: 12,
    yield_strength_mpa: 8,
    elastic_modulus_gpa: 20,
    hardness_vickers: 8,
    thermal_conductivity_w_mk: 21,
    specific_heat_j_gk: 0.22,
    melting_point_c: 72,
    glass_transition_c: null,
    max_service_temp_c: 50,
    thermal_expansion_ppm_k: 20,
    electrical_resistivity_ohm_m: 2.9e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 350,
    tags: ["low-temp-solder", "heat-sensitive", "cryogenic"],
    data_source: "Indium Corporation datasheet"
  },
  {
    id: "snbi42",
    name: "Sn58Bi42 Low-Temp Solder",
    category: "Solder",
    subcategory: "Tin-Bismuth",
    density_g_cm3: 8.56,
    tensile_strength_mpa: 58,
    yield_strength_mpa: 40,
    elastic_modulus_gpa: 42,
    hardness_vickers: 22,
    thermal_conductivity_w_mk: 19,
    specific_heat_j_gk: 0.21,
    melting_point_c: 138,
    glass_transition_c: null,
    max_service_temp_c: 80,
    thermal_expansion_ppm_k: 15,
    electrical_resistivity_ohm_m: 3.3e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 30,
    tags: ["low-temp", "lead-free", "heat-sensitive-assembly"],
    data_source: "Alpha Assembly Solutions datasheet"
  },
  {
    id: "sn96ag4",
    name: "Sn96Ag4 Silver Solder",
    category: "Solder",
    subcategory: "Tin-Silver",
    density_g_cm3: 7.4,
    tensile_strength_mpa: 55,
    yield_strength_mpa: 42,
    elastic_modulus_gpa: 50,
    hardness_vickers: 18,
    thermal_conductivity_w_mk: 57,
    specific_heat_j_gk: 0.23,
    melting_point_c: 221,
    glass_transition_c: null,
    max_service_temp_c: 130,
    thermal_expansion_ppm_k: 22,
    electrical_resistivity_ohm_m: 1.2e-7,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 40,
    tags: ["lead-free", "plumbing", "electronics", "rohs"],
    data_source: "MatWeb"
  }
];

export default handCuratedDB;
