import { Material } from "@/types";

const metalsSource = "ASM Handbook Vol. 2; MatWeb typical room-temperature values";
const polymersSource = "MatWeb polymer datasheets; OEM processing data";
const ceramicsSource = "MatWeb ceramics data; ASM engineered materials tables";
const compositesSource = "MatWeb composites data; manufacturer technical datasheets";
const soldersSource = "ASM specialty alloys data; supplier datasheets";

export const materialsDB: Material[] = [
  {
    id: "ss-316l",
    name: "Stainless Steel 316L",
    category: "Metal",
    subcategory: "Austenitic stainless steel",
    density_g_cm3: 8.0,
    tensile_strength_mpa: 580,
    yield_strength_mpa: 290,
    elastic_modulus_gpa: 193,
    hardness_vickers: 150,
    thermal_conductivity_w_mk: 16,
    specific_heat_j_gk: 0.5,
    melting_point_c: 1375,
    glass_transition_c: null,
    max_service_temp_c: 870,
    thermal_expansion_ppm_k: 16,
    electrical_resistivity_ohm_m: 7.4e-7,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 6.5,
    tags: ["stainless", "marine", "chemical service"],
    data_source: metalsSource
  },
  {
    id: "ti-6al-4v",
    name: "Ti-6Al-4V",
    category: "Metal",
    subcategory: "Alpha-beta titanium alloy",
    density_g_cm3: 4.43,
    tensile_strength_mpa: 950,
    yield_strength_mpa: 880,
    elastic_modulus_gpa: 114,
    hardness_vickers: 349,
    thermal_conductivity_w_mk: 6.7,
    specific_heat_j_gk: 0.526,
    melting_point_c: 1604,
    glass_transition_c: null,
    max_service_temp_c: 400,
    thermal_expansion_ppm_k: 8.6,
    electrical_resistivity_ohm_m: 1.71e-6,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 35,
    tags: ["aerospace", "biocompatible", "high specific strength"],
    data_source: metalsSource
  },
  {
    id: "inconel-718",
    name: "Inconel 718",
    category: "Metal",
    subcategory: "Nickel superalloy",
    density_g_cm3: 8.19,
    tensile_strength_mpa: 1240,
    yield_strength_mpa: 1030,
    elastic_modulus_gpa: 200,
    hardness_vickers: 330,
    thermal_conductivity_w_mk: 11.4,
    specific_heat_j_gk: 0.435,
    melting_point_c: 1336,
    glass_transition_c: null,
    max_service_temp_c: 700,
    thermal_expansion_ppm_k: 13,
    electrical_resistivity_ohm_m: 1.25e-6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 48,
    tags: ["superalloy", "high temperature", "fatigue resistant"],
    data_source: metalsSource
  },
  {
    id: "al-6061-t6",
    name: "Aluminum 6061-T6",
    category: "Metal",
    subcategory: "Heat-treated aluminum alloy",
    density_g_cm3: 2.7,
    tensile_strength_mpa: 310,
    yield_strength_mpa: 276,
    elastic_modulus_gpa: 68.9,
    hardness_vickers: 107,
    thermal_conductivity_w_mk: 167,
    specific_heat_j_gk: 0.896,
    melting_point_c: 582,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 23.6,
    electrical_resistivity_ohm_m: 4e-8,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 4.8,
    tags: ["general purpose", "lightweight", "machinable"],
    data_source: metalsSource
  },
  {
    id: "al-7075-t6",
    name: "Aluminum 7075-T6",
    category: "Metal",
    subcategory: "High-strength aluminum alloy",
    density_g_cm3: 2.81,
    tensile_strength_mpa: 572,
    yield_strength_mpa: 503,
    elastic_modulus_gpa: 71.7,
    hardness_vickers: 175,
    thermal_conductivity_w_mk: 130,
    specific_heat_j_gk: 0.96,
    melting_point_c: 477,
    glass_transition_c: null,
    max_service_temp_c: 120,
    thermal_expansion_ppm_k: 23.5,
    electrical_resistivity_ohm_m: 5.15e-8,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 6.8,
    tags: ["airframe", "high strength", "lightweight"],
    data_source: metalsSource
  },
  {
    id: "copper-c110",
    name: "Copper C110",
    category: "Metal",
    subcategory: "Electrolytic tough pitch copper",
    density_g_cm3: 8.96,
    tensile_strength_mpa: 220,
    yield_strength_mpa: 69,
    elastic_modulus_gpa: 117,
    hardness_vickers: 80,
    thermal_conductivity_w_mk: 391,
    specific_heat_j_gk: 0.385,
    melting_point_c: 1083,
    glass_transition_c: null,
    max_service_temp_c: 200,
    thermal_expansion_ppm_k: 16.5,
    electrical_resistivity_ohm_m: 1.68e-8,
    corrosion_resistance: "good",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 9.2,
    tags: ["electrical", "thermal", "busbar"],
    data_source: metalsSource
  },
  {
    id: "brass-c360",
    name: "Brass C360",
    category: "Metal",
    subcategory: "Free-machining brass",
    density_g_cm3: 8.49,
    tensile_strength_mpa: 338,
    yield_strength_mpa: 124,
    elastic_modulus_gpa: 97,
    hardness_vickers: 97,
    thermal_conductivity_w_mk: 115,
    specific_heat_j_gk: 0.377,
    melting_point_c: 885,
    glass_transition_c: null,
    max_service_temp_c: 200,
    thermal_expansion_ppm_k: 20.5,
    electrical_resistivity_ohm_m: 6.2e-8,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "n/a",
    cost_usd_kg: 6.4,
    tags: ["machinable", "fittings", "connector hardware"],
    data_source: metalsSource
  },
  {
    id: "bronze-c932",
    name: "Bronze C932",
    category: "Metal",
    subcategory: "Bearing bronze",
    density_g_cm3: 8.83,
    tensile_strength_mpa: 250,
    yield_strength_mpa: 140,
    elastic_modulus_gpa: 103,
    hardness_vickers: 65,
    thermal_conductivity_w_mk: 63,
    specific_heat_j_gk: 0.377,
    melting_point_c: 985,
    glass_transition_c: null,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 18,
    electrical_resistivity_ohm_m: 8.5e-8,
    corrosion_resistance: "good",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 7.8,
    tags: ["bearing", "wear", "sleeve"],
    data_source: metalsSource
  },
  {
    id: "monel-400",
    name: "Monel 400",
    category: "Metal",
    subcategory: "Nickel-copper alloy",
    density_g_cm3: 8.8,
    tensile_strength_mpa: 550,
    yield_strength_mpa: 240,
    elastic_modulus_gpa: 179,
    hardness_vickers: 150,
    thermal_conductivity_w_mk: 21.8,
    specific_heat_j_gk: 0.427,
    melting_point_c: 1350,
    glass_transition_c: null,
    max_service_temp_c: 480,
    thermal_expansion_ppm_k: 13.9,
    electrical_resistivity_ohm_m: 4.9e-7,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 22,
    tags: ["seawater", "chemical handling", "monel"],
    data_source: metalsSource
  },
  {
    id: "hastelloy-c276",
    name: "Hastelloy C-276",
    category: "Metal",
    subcategory: "Corrosion-resistant nickel alloy",
    density_g_cm3: 8.89,
    tensile_strength_mpa: 790,
    yield_strength_mpa: 355,
    elastic_modulus_gpa: 205,
    hardness_vickers: 230,
    thermal_conductivity_w_mk: 10.2,
    specific_heat_j_gk: 0.427,
    melting_point_c: 1325,
    glass_transition_c: null,
    max_service_temp_c: 1040,
    thermal_expansion_ppm_k: 12.4,
    electrical_resistivity_ohm_m: 1.3e-6,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 62,
    tags: ["acid service", "chlorides", "process plant"],
    data_source: metalsSource
  },
  {
    id: "tungsten",
    name: "Tungsten",
    category: "Metal",
    subcategory: "Refractory metal",
    density_g_cm3: 19.25,
    tensile_strength_mpa: 980,
    yield_strength_mpa: 750,
    elastic_modulus_gpa: 411,
    hardness_vickers: 343,
    thermal_conductivity_w_mk: 174,
    specific_heat_j_gk: 0.134,
    melting_point_c: 3422,
    glass_transition_c: null,
    max_service_temp_c: 2500,
    thermal_expansion_ppm_k: 4.5,
    electrical_resistivity_ohm_m: 5.6e-8,
    corrosion_resistance: "good",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 40,
    tags: ["refractory", "high temperature", "radiation shielding"],
    data_source: metalsSource
  },
  {
    id: "molybdenum",
    name: "Molybdenum",
    category: "Metal",
    subcategory: "Refractory metal",
    density_g_cm3: 10.28,
    tensile_strength_mpa: 690,
    yield_strength_mpa: 550,
    elastic_modulus_gpa: 329,
    hardness_vickers: 230,
    thermal_conductivity_w_mk: 138,
    specific_heat_j_gk: 0.251,
    melting_point_c: 2623,
    glass_transition_c: null,
    max_service_temp_c: 1100,
    thermal_expansion_ppm_k: 5.1,
    electrical_resistivity_ohm_m: 5.3e-8,
    corrosion_resistance: "fair",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 32,
    tags: ["high temperature", "stiff", "furnace hardware"],
    data_source: metalsSource
  },
  {
    id: "becu-c17200",
    name: "Beryllium Copper C17200",
    category: "Metal",
    subcategory: "Precipitation-hardened copper alloy",
    density_g_cm3: 8.25,
    tensile_strength_mpa: 1140,
    yield_strength_mpa: 1035,
    elastic_modulus_gpa: 131,
    hardness_vickers: 350,
    thermal_conductivity_w_mk: 105,
    specific_heat_j_gk: 0.42,
    melting_point_c: 866,
    glass_transition_c: null,
    max_service_temp_c: 315,
    thermal_expansion_ppm_k: 17,
    electrical_resistivity_ohm_m: 7.2e-8,
    corrosion_resistance: "good",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 25,
    tags: ["spring contact", "conductive", "wear resistant"],
    data_source: metalsSource
  },
  {
    id: "nickel-200",
    name: "Nickel 200",
    category: "Metal",
    subcategory: "Commercially pure nickel",
    density_g_cm3: 8.89,
    tensile_strength_mpa: 462,
    yield_strength_mpa: 148,
    elastic_modulus_gpa: 204,
    hardness_vickers: 110,
    thermal_conductivity_w_mk: 60.7,
    specific_heat_j_gk: 0.444,
    melting_point_c: 1455,
    glass_transition_c: null,
    max_service_temp_c: 600,
    thermal_expansion_ppm_k: 13.3,
    electrical_resistivity_ohm_m: 6.99e-8,
    corrosion_resistance: "good",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 18,
    tags: ["caustic service", "conductive", "nickel"],
    data_source: metalsSource
  },
  {
    id: "tool-steel-d2",
    name: "Tool Steel D2",
    category: "Metal",
    subcategory: "High-carbon high-chromium tool steel",
    density_g_cm3: 7.7,
    tensile_strength_mpa: 760,
    yield_strength_mpa: 450,
    elastic_modulus_gpa: 210,
    hardness_vickers: 700,
    thermal_conductivity_w_mk: 20,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1421,
    glass_transition_c: null,
    max_service_temp_c: 425,
    thermal_expansion_ppm_k: 10.4,
    electrical_resistivity_ohm_m: 6e-7,
    corrosion_resistance: "fair",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 7.5,
    tags: ["tooling", "wear", "hardness"],
    data_source: metalsSource
  },
  {
    id: "spring-steel-1095",
    name: "Spring Steel 1095",
    category: "Metal",
    subcategory: "High-carbon spring steel",
    density_g_cm3: 7.85,
    tensile_strength_mpa: 965,
    yield_strength_mpa: 580,
    elastic_modulus_gpa: 205,
    hardness_vickers: 240,
    thermal_conductivity_w_mk: 49.8,
    specific_heat_j_gk: 0.49,
    melting_point_c: 1480,
    glass_transition_c: null,
    max_service_temp_c: 220,
    thermal_expansion_ppm_k: 11.6,
    electrical_resistivity_ohm_m: 1.43e-7,
    corrosion_resistance: "poor",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 2.3,
    tags: ["springs", "elastic", "high carbon"],
    data_source: metalsSource
  },
  {
    id: "carbon-steel-1020",
    name: "Carbon Steel 1020",
    category: "Metal",
    subcategory: "Low-carbon steel",
    density_g_cm3: 7.87,
    tensile_strength_mpa: 420,
    yield_strength_mpa: 350,
    elastic_modulus_gpa: 205,
    hardness_vickers: 120,
    thermal_conductivity_w_mk: 51.9,
    specific_heat_j_gk: 0.486,
    melting_point_c: 1515,
    glass_transition_c: null,
    max_service_temp_c: 300,
    thermal_expansion_ppm_k: 11.7,
    electrical_resistivity_ohm_m: 1.59e-7,
    corrosion_resistance: "poor",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 1.2,
    tags: ["structural", "economical", "weldable"],
    data_source: metalsSource
  },
  {
    id: "grey-cast-iron",
    name: "Grey Cast Iron",
    category: "Metal",
    subcategory: "Cast iron",
    density_g_cm3: 7.15,
    tensile_strength_mpa: 240,
    yield_strength_mpa: 130,
    elastic_modulus_gpa: 110,
    hardness_vickers: 200,
    thermal_conductivity_w_mk: 46,
    specific_heat_j_gk: 0.46,
    melting_point_c: 1150,
    glass_transition_c: null,
    max_service_temp_c: 400,
    thermal_expansion_ppm_k: 10.5,
    electrical_resistivity_ohm_m: 8.5e-7,
    corrosion_resistance: "fair",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 1.6,
    tags: ["damping", "castable", "machine base"],
    data_source: metalsSource
  },
  {
    id: "pla",
    name: "PLA",
    category: "Polymer",
    subcategory: "Polylactic acid",
    density_g_cm3: 1.24,
    tensile_strength_mpa: 60,
    yield_strength_mpa: 50,
    elastic_modulus_gpa: 3.5,
    hardness_vickers: 15,
    thermal_conductivity_w_mk: 0.13,
    specific_heat_j_gk: 1.8,
    melting_point_c: null,
    glass_transition_c: 60,
    max_service_temp_c: 55,
    thermal_expansion_ppm_k: 68,
    electrical_resistivity_ohm_m: 1e13,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "excellent",
    cost_usd_kg: 22,
    tags: ["fdm", "prototype", "biopolymer"],
    data_source: polymersSource
  },
  {
    id: "abs",
    name: "ABS",
    category: "Polymer",
    subcategory: "Acrylonitrile butadiene styrene",
    density_g_cm3: 1.04,
    tensile_strength_mpa: 40,
    yield_strength_mpa: 32,
    elastic_modulus_gpa: 2.2,
    hardness_vickers: 12,
    thermal_conductivity_w_mk: 0.18,
    specific_heat_j_gk: 1.3,
    melting_point_c: null,
    glass_transition_c: 105,
    max_service_temp_c: 85,
    thermal_expansion_ppm_k: 90,
    electrical_resistivity_ohm_m: 1e13,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "good",
    cost_usd_kg: 20,
    tags: ["impact resistant", "fdm", "consumer enclosures"],
    data_source: polymersSource
  },
  {
    id: "petg",
    name: "PETG",
    category: "Polymer",
    subcategory: "Glycol-modified PET",
    density_g_cm3: 1.27,
    tensile_strength_mpa: 53,
    yield_strength_mpa: 50,
    elastic_modulus_gpa: 2.1,
    hardness_vickers: 14,
    thermal_conductivity_w_mk: 0.2,
    specific_heat_j_gk: 1.2,
    melting_point_c: null,
    glass_transition_c: 80,
    max_service_temp_c: 85,
    thermal_expansion_ppm_k: 65,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "excellent",
    cost_usd_kg: 24,
    tags: ["fdm", "tough", "chemical resistant"],
    data_source: polymersSource
  },
  {
    id: "nylon-pa12",
    name: "Nylon PA12",
    category: "Polymer",
    subcategory: "Polyamide 12",
    density_g_cm3: 1.01,
    tensile_strength_mpa: 48,
    yield_strength_mpa: 45,
    elastic_modulus_gpa: 1.7,
    hardness_vickers: 10,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1.7,
    melting_point_c: null,
    glass_transition_c: 50,
    max_service_temp_c: 110,
    thermal_expansion_ppm_k: 100,
    electrical_resistivity_ohm_m: 1e11,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "good",
    cost_usd_kg: 58,
    tags: ["wear", "low density", "functional print"],
    data_source: polymersSource
  },
  {
    id: "polycarbonate",
    name: "Polycarbonate",
    category: "Polymer",
    subcategory: "Engineering thermoplastic",
    density_g_cm3: 1.2,
    tensile_strength_mpa: 65,
    yield_strength_mpa: 62,
    elastic_modulus_gpa: 2.3,
    hardness_vickers: 18,
    thermal_conductivity_w_mk: 0.2,
    specific_heat_j_gk: 1.2,
    melting_point_c: null,
    glass_transition_c: 147,
    max_service_temp_c: 120,
    thermal_expansion_ppm_k: 65,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "fair",
    cost_usd_kg: 42,
    tags: ["impact resistant", "transparent", "electrical housing"],
    data_source: polymersSource
  },
  {
    id: "peek",
    name: "PEEK",
    category: "Polymer",
    subcategory: "High-performance thermoplastic",
    density_g_cm3: 1.3,
    tensile_strength_mpa: 100,
    yield_strength_mpa: 95,
    elastic_modulus_gpa: 3.6,
    hardness_vickers: 22,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1.3,
    melting_point_c: null,
    glass_transition_c: 143,
    max_service_temp_c: 250,
    thermal_expansion_ppm_k: 47,
    electrical_resistivity_ohm_m: 1e16,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "fair",
    cost_usd_kg: 330,
    tags: ["high temperature", "chemical resistant", "medical"],
    data_source: polymersSource
  },
  {
    id: "ultem-9085",
    name: "Ultem 9085",
    category: "Polymer",
    subcategory: "PEI aerospace-grade filament",
    density_g_cm3: 1.34,
    tensile_strength_mpa: 69,
    yield_strength_mpa: 67,
    elastic_modulus_gpa: 2.5,
    hardness_vickers: 20,
    thermal_conductivity_w_mk: 0.22,
    specific_heat_j_gk: 1.25,
    melting_point_c: null,
    glass_transition_c: 186,
    max_service_temp_c: 170,
    thermal_expansion_ppm_k: 55,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "good",
    cost_usd_kg: 190,
    tags: ["high-end FDM", "flame resistant", "aerospace"],
    data_source: polymersSource
  },
  {
    id: "ptfe",
    name: "PTFE",
    category: "Polymer",
    subcategory: "Fluoropolymer",
    density_g_cm3: 2.2,
    tensile_strength_mpa: 25,
    yield_strength_mpa: 20,
    elastic_modulus_gpa: 0.5,
    hardness_vickers: 5,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1,
    melting_point_c: null,
    glass_transition_c: 115,
    max_service_temp_c: 260,
    thermal_expansion_ppm_k: 120,
    electrical_resistivity_ohm_m: 1e18,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "poor",
    cost_usd_kg: 18,
    tags: ["nonstick", "chemical inertness", "insulator"],
    data_source: polymersSource
  },
  {
    id: "hdpe",
    name: "HDPE",
    category: "Polymer",
    subcategory: "High-density polyethylene",
    density_g_cm3: 0.95,
    tensile_strength_mpa: 31,
    yield_strength_mpa: 26,
    elastic_modulus_gpa: 0.9,
    hardness_vickers: 6,
    thermal_conductivity_w_mk: 0.5,
    specific_heat_j_gk: 1.9,
    melting_point_c: null,
    glass_transition_c: -110,
    max_service_temp_c: 80,
    thermal_expansion_ppm_k: 130,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "fair",
    cost_usd_kg: 8,
    tags: ["chemical tank", "lightweight", "low cost"],
    data_source: polymersSource
  },
  {
    id: "delrin-pom",
    name: "Delrin (POM)",
    category: "Polymer",
    subcategory: "Acetal homopolymer",
    density_g_cm3: 1.41,
    tensile_strength_mpa: 72,
    yield_strength_mpa: 69,
    elastic_modulus_gpa: 2.9,
    hardness_vickers: 16,
    thermal_conductivity_w_mk: 0.31,
    specific_heat_j_gk: 1.46,
    melting_point_c: null,
    glass_transition_c: -60,
    max_service_temp_c: 105,
    thermal_expansion_ppm_k: 110,
    electrical_resistivity_ohm_m: 1e14,
    corrosion_resistance: "good",
    machinability: "excellent",
    printability_fdm: "fair",
    cost_usd_kg: 17,
    tags: ["precision parts", "gears", "low friction"],
    data_source: polymersSource
  },
  {
    id: "polysulfone",
    name: "Polysulfone",
    category: "Polymer",
    subcategory: "Amorphous engineering thermoplastic",
    density_g_cm3: 1.24,
    tensile_strength_mpa: 70,
    yield_strength_mpa: 68,
    elastic_modulus_gpa: 2.6,
    hardness_vickers: 20,
    thermal_conductivity_w_mk: 0.26,
    specific_heat_j_gk: 1.1,
    melting_point_c: null,
    glass_transition_c: 185,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 56,
    electrical_resistivity_ohm_m: 1e15,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "fair",
    cost_usd_kg: 75,
    tags: ["sterilizable", "hot water service", "transparent amber"],
    data_source: polymersSource
  },
  {
    id: "alumina",
    name: "Alumina Al2O3",
    category: "Ceramic",
    subcategory: "Engineering ceramic",
    density_g_cm3: 3.95,
    tensile_strength_mpa: 300,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 380,
    hardness_vickers: 1500,
    thermal_conductivity_w_mk: 30,
    specific_heat_j_gk: 0.88,
    melting_point_c: 2050,
    glass_transition_c: null,
    max_service_temp_c: 1650,
    thermal_expansion_ppm_k: 8,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 35,
    tags: ["insulator", "wear resistant", "high hardness"],
    data_source: ceramicsSource
  },
  {
    id: "zirconia",
    name: "Zirconia ZrO2",
    category: "Ceramic",
    subcategory: "Transformation-toughened ceramic",
    density_g_cm3: 6.05,
    tensile_strength_mpa: 900,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 210,
    hardness_vickers: 1200,
    thermal_conductivity_w_mk: 2.5,
    specific_heat_j_gk: 0.5,
    melting_point_c: 2715,
    glass_transition_c: null,
    max_service_temp_c: 1000,
    thermal_expansion_ppm_k: 10.5,
    electrical_resistivity_ohm_m: 1e10,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 60,
    tags: ["bioceramic", "tough ceramic", "thermal barrier"],
    data_source: ceramicsSource
  },
  {
    id: "silicon-carbide",
    name: "Silicon Carbide SiC",
    category: "Ceramic",
    subcategory: "Non-oxide ceramic",
    density_g_cm3: 3.21,
    tensile_strength_mpa: 350,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 410,
    hardness_vickers: 2500,
    thermal_conductivity_w_mk: 120,
    specific_heat_j_gk: 0.75,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 1600,
    thermal_expansion_ppm_k: 4,
    electrical_resistivity_ohm_m: 0.01,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 80,
    tags: ["abrasive", "hot section", "high thermal conductivity"],
    data_source: ceramicsSource
  },
  {
    id: "silicon-nitride",
    name: "Silicon Nitride Si3N4",
    category: "Ceramic",
    subcategory: "Structural ceramic",
    density_g_cm3: 3.24,
    tensile_strength_mpa: 800,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 300,
    hardness_vickers: 1550,
    thermal_conductivity_w_mk: 30,
    specific_heat_j_gk: 0.8,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 1200,
    thermal_expansion_ppm_k: 3.2,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 95,
    tags: ["bearing", "thermal shock", "engine components"],
    data_source: ceramicsSource
  },
  {
    id: "boron-nitride",
    name: "Boron Nitride BN",
    category: "Ceramic",
    subcategory: "Hexagonal boron nitride",
    density_g_cm3: 2.25,
    tensile_strength_mpa: 35,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 30,
    hardness_vickers: 30,
    thermal_conductivity_w_mk: 60,
    specific_heat_j_gk: 0.79,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 900,
    thermal_expansion_ppm_k: 1.5,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "good",
    printability_fdm: "n/a",
    cost_usd_kg: 110,
    tags: ["machinable ceramic", "thermal management", "electrical insulation"],
    data_source: ceramicsSource
  },
  {
    id: "cfrp-ud",
    name: "CFRP (Carbon Fiber UD)",
    category: "Composite",
    subcategory: "Unidirectional carbon/epoxy laminate",
    density_g_cm3: 1.6,
    tensile_strength_mpa: 1500,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 135,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 8,
    specific_heat_j_gk: 0.8,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 180,
    thermal_expansion_ppm_k: 0.2,
    electrical_resistivity_ohm_m: 1e-5,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 65,
    tags: ["high specific stiffness", "aerospace", "composite"],
    data_source: compositesSource
  },
  {
    id: "gfrp",
    name: "GFRP",
    category: "Composite",
    subcategory: "Glass fiber reinforced polymer",
    density_g_cm3: 1.85,
    tensile_strength_mpa: 900,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 40,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.35,
    specific_heat_j_gk: 0.9,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 120,
    thermal_expansion_ppm_k: 8,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 18,
    tags: ["marine", "low cost composite", "insulating"],
    data_source: compositesSource
  },
  {
    id: "kevlar-epoxy",
    name: "Kevlar/Epoxy",
    category: "Composite",
    subcategory: "Aramid fiber reinforced epoxy",
    density_g_cm3: 1.38,
    tensile_strength_mpa: 1000,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 70,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 0.25,
    specific_heat_j_gk: 1.4,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: -2,
    electrical_resistivity_ohm_m: 1e12,
    corrosion_resistance: "excellent",
    machinability: "poor",
    printability_fdm: "n/a",
    cost_usd_kg: 42,
    tags: ["impact resistant", "ballistic", "tough composite"],
    data_source: compositesSource
  },
  {
    id: "carbon-carbon",
    name: "Carbon-Carbon",
    category: "Composite",
    subcategory: "Carbon fiber reinforced carbon matrix",
    density_g_cm3: 1.75,
    tensile_strength_mpa: 160,
    yield_strength_mpa: 0,
    elastic_modulus_gpa: 60,
    hardness_vickers: null,
    thermal_conductivity_w_mk: 25,
    specific_heat_j_gk: 0.71,
    melting_point_c: null,
    glass_transition_c: null,
    max_service_temp_c: 2000,
    thermal_expansion_ppm_k: 1,
    electrical_resistivity_ohm_m: 3e-5,
    corrosion_resistance: "good",
    machinability: "fair",
    printability_fdm: "n/a",
    cost_usd_kg: 450,
    tags: ["ultra high temperature", "brakes", "thermal shock"],
    data_source: compositesSource
  },
  {
    id: "sn63pb37",
    name: "Sn63Pb37",
    category: "Solder",
    subcategory: "Eutectic tin-lead solder",
    density_g_cm3: 8.4,
    tensile_strength_mpa: 55,
    yield_strength_mpa: 38,
    elastic_modulus_gpa: 30,
    hardness_vickers: 18,
    thermal_conductivity_w_mk: 50,
    specific_heat_j_gk: 0.16,
    melting_point_c: 183,
    glass_transition_c: null,
    max_service_temp_c: 125,
    thermal_expansion_ppm_k: 24,
    electrical_resistivity_ohm_m: 1.45e-7,
    corrosion_resistance: "fair",
    machinability: "n/a",
    printability_fdm: "n/a",
    cost_usd_kg: 24,
    tags: ["electronics", "eutectic", "legacy assembly"],
    data_source: soldersSource
  },
  {
    id: "sac305",
    name: "SAC305",
    category: "Solder",
    subcategory: "Lead-free Sn-Ag-Cu solder",
    density_g_cm3: 7.38,
    tensile_strength_mpa: 57,
    yield_strength_mpa: 37,
    elastic_modulus_gpa: 50,
    hardness_vickers: 15,
    thermal_conductivity_w_mk: 62,
    specific_heat_j_gk: 0.22,
    melting_point_c: 217,
    glass_transition_c: null,
    max_service_temp_c: 150,
    thermal_expansion_ppm_k: 22,
    electrical_resistivity_ohm_m: 1.3e-7,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "n/a",
    cost_usd_kg: 34,
    tags: ["lead free", "surface mount", "bga"],
    data_source: soldersSource
  },
  {
    id: "gold-tin-ausn20",
    name: "Gold-Tin AuSn20",
    category: "Solder",
    subcategory: "High-reliability eutectic solder",
    density_g_cm3: 14.5,
    tensile_strength_mpa: 275,
    yield_strength_mpa: 210,
    elastic_modulus_gpa: 68,
    hardness_vickers: 190,
    thermal_conductivity_w_mk: 57,
    specific_heat_j_gk: 0.15,
    melting_point_c: 280,
    glass_transition_c: null,
    max_service_temp_c: 250,
    thermal_expansion_ppm_k: 16,
    electrical_resistivity_ohm_m: 1.6e-7,
    corrosion_resistance: "excellent",
    machinability: "n/a",
    printability_fdm: "n/a",
    cost_usd_kg: 1800,
    tags: ["hermetic package", "space electronics", "premium solder"],
    data_source: soldersSource
  },
  {
    id: "silver-braze-bag7",
    name: "Silver Braze BAg-7",
    category: "Solder",
    subcategory: "Silver-copper-phosphorus brazing alloy",
    density_g_cm3: 9.3,
    tensile_strength_mpa: 520,
    yield_strength_mpa: 310,
    elastic_modulus_gpa: 76,
    hardness_vickers: 95,
    thermal_conductivity_w_mk: 110,
    specific_heat_j_gk: 0.23,
    melting_point_c: 650,
    glass_transition_c: null,
    max_service_temp_c: 315,
    thermal_expansion_ppm_k: 19,
    electrical_resistivity_ohm_m: 3.5e-8,
    corrosion_resistance: "good",
    machinability: "n/a",
    printability_fdm: "n/a",
    cost_usd_kg: 85,
    tags: ["brazing", "heat exchanger", "high conductivity"],
    data_source: soldersSource
  }
];
